name: 1.16.5 Publish Tasks

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Target Platform to publish. Values: all, modrinth, curseforge'
        default: 'all'
        required: true
        options:
          - all
          - modrinth
          - curseforge

permissions:
  contents: read

jobs:
  publish-to-modrinth:
    runs-on: ubuntu-latest
    if: github.event.inputs.platform == 'modrinth' || github.event.inputs.platform == 'all'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '1.16.5'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
  publish-to-curseforge:
    runs-on: ubuntu-latest
    if: github.event.inputs.platform == 'curseforge' || github.event.inputs.platform == 'all'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '1.16.5'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build