name: 1.19.X Publish Tasks

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Target Platform to publish. Values: all, modrinth, curseforge'
        default: 'all'
        required: true
        options:
          - all
          - modrinth
          - curseforge

permissions:
  contents: read

jobs:
  publish-to-modrinth:
    runs-on: ubuntu-latest
    if: github.event.inputs.platform == 'modrinth' || github.event.inputs.platform == 'all'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '1.19'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Upload with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: modrinthnnu4dJj4
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  publish-to-curseforge:
    runs-on: ubuntu-latest
    if: github.event.inputs.platform == 'curseforge' || github.event.inputs.platform == 'all'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '1.19'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Upload with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: curseforge622165
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}